---
version: '3'
services:
  dry:
    build:
       context: .
       dockerfile: "./docker/Dockerfile.custom"
    container_name: my-freqtrade-dry-run
    volumes:
      - "./user_data:/freqtrade/user_data"
    command: >
      trade
      --strategy TheMessenger
      --config user_data/config.json
      --config user_data/pairlist-volume-gateio-usdt.json
  backtesting:
    build:
       context: .
       dockerfile: "./docker/Dockerfile.custom"
    container_name: my-freqtrade-backtesting
    volumes:
      - "./user_data:/freqtrade/user_data"
    command: >
      backtesting
      --strategy-list NFIX_BB_RPB_v103 NFIX_BB_RPB_v104 NostalgiaForInfinityX NostalgiaForInfinityNext NostalgiaForInfinityNext_v772 NostalgiaForInfinityNextGen BB_RPB_TSL_v102 BB_RPB_TSL_v103 BB_RPB_TSL_v104
      --timerange ${TIMERANGE:-20211101-20211115}
      --config user_data/data/pairlists.json
      --config user_data/data/${EXCHANGE:-gateio}-usdt-static.json
      --max-open-trades ${MAX_OPEN_TRADES:-5}
      --stake-amount ${STAKE_AMOUNT:-unlimited}
      --breakdown day month
  download-data:
    image: freqtradeorg/freqtrade:develop
    container_name: my-download-data
    volumes:
      - "./user_data:/freqtrade/user_data"
    command: >
      download-data
      --timerange ${START_DATE:-20211101}-${END_DATE:-20211201}
      --timeframe 5m 15m 1h 1d
      --datadir user_data/data/${EXCHANGE:-kucoin}
      --config user_data/data/pairlists.json
      --config user_data/data/${EXCHANGE:-kucoin}-usdt-static.json
