---
version: '3'
services:
  backtesting:
    build:
       context: .
       dockerfile: "./docker/Dockerfile.custom"
    container_name: my-freqtrade-backtesting
    volumes:
      - "./user_data:/freqtrade/user_data"
    command: >
      backtesting
      --strategy-list NFIX_BB_RPB
      --timerange ${TIMERANGE:-20210801-20211101}
      --config user_data/data/pairlists.json
      --config user_data/data/${EXCHANGE:-kucoin}-usdt-static.json
      --max-open-trades ${MAX_OPEN_TRADES:-5}
      --stake-amount ${STAKE_AMOUNT:-unlimited}
      --breakdown day month
  download-data:
    image: freqtradeorg/freqtrade:develop
    container_name: my-download-data
    volumes:
      - "./user_data:/freqtrade/user_data"
    command: >
      download-data
      --timerange ${START_DATE:-20210101}-${END_DATE:-20211101}
      --timeframe 5m 15m 1h
      --datadir user_data/data/${EXCHANGE:-kucoin}
      --config user_data/data/pairlists.json
      --config user_data/data/${EXCHANGE:-kucoin}-usdt-static.json
